# Site settings
title: Austin Copeman
email: contactme@austincopeman.com
url: http://www.austincopeman.com/
page-url: http://www.austincopeman.com/cit337
description: "Course: CIT 337 - Software Engineer and Practice; Descrition of the course and files that were a part of the course"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: www.austincopeman.com

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/austincopeman
  - title: google-plus
    url: https://plus.google.com/+AustinCopeman/posts
  - title: github
    url: https://github.com/acope

# Build settings
markdown: kramdown
permalink: pretty
